# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=docs

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install 'virtualenv<16.0'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install 'setuptools<40.0'; fi

# command to run tests, e.g. python setup.py test
script: tox
